### ISSUE TITLE
Project name conflict

### ISSUE THREAD

**Issue by iredmail** [lucas1/Perl-iRedAdmin#1]
Dear @lucas1 ,

Your project name conflicts with the official iRedMail admin panel - iRedAdmin. It's recommended to use a different name, and mention in project description that this is an unofficial iRedMail project.

Thanks for your interest in iRedMail. :)

**Comment by lucas1** [comment]
Ok, I will change name.

**Comment by iredmail** [comment]
Dear @lucas1,

You're still using the term "iredadmin" in your program (perl-iredadmin), this conflicts with the our official product "iRedAdmin". Could you please change it? Maybe 'perl-iredmail-admin' or another one you prefer. :)

Just want to avoid confusion to our customers, they may think this is a Perl edition of our official admin tool.
